### ISSUE TITLE
Landscape issue

### ISSUE THREAD

**Issue by buetforasif** [nimati/FCAlertView#31] opened 2016-11-23 08:40 UTC
Please add support for apps in landscape orientation.

**Comment by nimati** [comment] 2016-11-23 08:41
Are you using the latest release? Landscape orientation should work, unless your app is using both portrait and landscape. In that case, there might be slight framing issues.

**Comment by buetforasif** [comment] 2016-11-23 08:50
Hi,
Yes, I am using the latest release. The app is landscape-only. 
I am sharing a screenshot from iPhone5 device --> http://imgur.com/a/Tyr5u

**Comment by nimati** [comment] 2016-11-23 08:53
Interesting, so the issue is that it's not in the center, correct?

**Comment by buetforasif** [comment] 2016-11-23 08:53
yes, not centered.

**Comment by nimati** [comment] 2016-11-23 08:54
Right, it also seems a little too wide compared to the frames I assigned it. Let me take a look at it and will let you know, hopefully within the next 24 hours or so. Thanks for pointing this out by the way!

**Comment by nimati** [comment] 2016-11-28 20:22
Hi @buetforasif 

I took a closer look and tried to re-create your alert, however I couldn't see the issue. It would centre everything right as you can see: http://imgur.com/a/SRoHi 

Can you send me the code you're using to generate the alert and all the customizations involved?

**Closed as completed** 2016-12-08 21:18 UTC
